### ISSUE TITLE
Decklink To UDP

### ISSUE THREAD

**Issue by sfahadshahzad** [sendust/gstreamer#1]
Hi,

Hope you are doing well.

Can you please guide me how I can create pipeline for decklink to stream strict CBR mpegts ?

Also I Need to upscale PAL SD signal into full hd from SDI input.

Thanks

Fahad

**Comment by sendust** [comment]
simplest way is get ffmpeg binary compiled with decklink sdk

ffmpeg  -f decklink -channels 8 -audio_depth 32 -queue_size 1000000000  -draw_bars 0 -format_code pal -raw_format uyvy422 -i "DeckLink Studio 4K" -filter_complex "[0:v]bwdif[deint];[deint]scale=w=1920:h=1080;[0:a]pan=stereo|c0=c0|c1=c1" -pix_fmt yuv420p -c:v mpeg2video -b:v 8000k -minrate 8000k -maxrate 8000k -bufsize 8000k -g 10 -bf 0 -c:a aac -ac 2 -f mpegts "udp://232.100.1.101:60000?ttl=10"

get pal video from decklink and deinterlace, upscale to 1080p and streaming udp with CBR, multicast address.

**Comment by sfahadshahzad** [comment]
Hi,

I am getting error ( av_interleaved_write_frame(): Cannot allocate memory) after two hours. 

Regards,

Fahad

**Comment by sendust** [comment]
p{margin-top:0;margin-bottom:0}
    


    Dear,Some tests are needed to narrow down the solution.1. Test the network for any problems    ffmpeg -f lavfi -re -i testsrc -c:v mpeg2video -f mpegts udp://233.1.2.3:800002. Check that there are no problems with the decklink input    ffmpeg -y -f dshow -r 29.97 -video_size 1920x1080 -rtbufsize 1400M -framerate 29.97 -top 1 -pixel_format uyvy422 -sample_rate 48000 -sample_size 16 -channels 4 -i "video=Decklink Video Capture:audio=Decklink Audio Capture" -pix_fmt yuv420p -c:v mpeg2video -f null -3. Change decklink driver version or compiled ffmpeg version4. ffmpeg can handle decklink two way.. one is directshow device, other is decklink native device   Try both of them..
--------- 원본 메일 ---------

    
        보낸사람: sfahadshahzad ***@***.***>
        받는사람: sendust/gstreamer ***@***.***>
        
            참조: sendust ***@***.***>, State change ***@***.***>
        
        날짜: 22.07.19 23:46 GMT +0900
        제목: Re: [sendust/gstreamer] Decklink To UDP (Issue #1)
        
        
    
    
        
Hi,
I am getting error ( av_interleaved_write_frame(): Cannot allocate memory) after two hours.
Regards,
Fahad

**Comment by sfahadshahzad** [comment]
Hi,

Do you have any idea how to compile ffmpeg with decklink in docker container ?

Regards,

Fahad
